name: First WorkFlow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello Vinay"
      - name: Multiline Command
        run: |
          node -v
          npm -v
